microsoft/electionguard-python

docs/4_Decrypt_Tally.md

Fixes #63 
Just cleaning up some spelling errors and name changes

Documentation clean up

---

src/electionguard/ballot.py
src/electionguard/chaum_pedersen.py
src/electionguard/decryption_mediator.py
src/electionguard/election_polynomial.py
src/electionguard/elgamal.py
src/electionguard/group.py
src/electionguard/key_ceremony.py
src/electionguard/logs.py
src/electionguard/tally.py
src/electionguard/tracker.py
src/electionguard/words.py

Related issue: https://github.com/microsoft/electionguard-python/issues/64
I made a pass through the code to see how all the new things work. I made a handful of fixes to remove warnings generated by PyCharm. The only notably new feature is that the logging wasn't correctly writing to files (stdout was fine). While I was at it, I added log rotation, so the disk logs will persist for longer. I also fixed a few spelling errors and tweaked some list comprehensions to be more concise.
I left a few TODO notes in the code for things that you might or might not want to address at some point in the future.
All unit tests still pass. Changes were entirely local, so shouldn't have disturbed anything.
💚Thank …

minor code cleanup

---

.github/workflows/release.yml
Makefile
Pipfile
Pipfile.lock
README.md
docs/Project_Workflow.md
docs/index.md
setup.py

Fixes #53 
Fixes #62 
Fixes #71 
Fixes #72 
Create a Release Workflow
- Create Package
- Create Dependency Graph
- Upload Package and Dependency Graph within workflow
- Upload Package and Dependency Graph within release
- Create Release
⚠️ ⚠️ ⚠️ PLEASE DO NOT CLOSE A MILESTONE TO TEST
See the actions that have been performed to see it working. This is currently set up to work with production.

Release and Packaging Workflow

---

README.md

n/a
Edits `README.md` to link to Dan Wallach's real home page, not Twitter
n/a
💚Thank you!

change README credits for Dan Wallach

---

setup.py

Fixes #106 
- Update setup.py to v1.1.0 for next release

✨ Update to v1.1.0

---

src/electionguard/publish.py
src/electionguard/serializable.py

Use os.path.join instead of separators for cleaner usage
Fixes #116 
Replace use of path.sep with path.join
- `test_publish`
💚Thank you!

✅  Use os.path.join

---

src/electionguard/decryption.py
src/electionguard/decryption_mediator.py
src/electionguard/key_ceremony_mediator.py
tests/test_decryption_mediator.py
tests/test_guardian.py
tests/test_key_ceremony.py
tests/test_key_ceremony_mediator.py

Fixes #103 
- Add identity encrypt / decrypt methods
- update methods to allow encrypt/decrypt override at higher levels
- update tests to use identity for speed
- run full test suite
💚Thank you!

Remove RSA from certain tests and CI for speed

---

Pipfile
Pipfile.lock
setup.py

Fixes #115 
- Add required_packages from pipfile to setup.py
- Update python version in setup.py
- Let CI run
💚Thank you!

Add packages from pipfile to setup

---

src/electionguard/ballot.py
src/electionguard/encrypt.py
src/electionguard/publish.py
src/electionguard/serializable.py
src/electionguard/utils.py
src/electionguardtest/data/ballot_in_simple.json
src/electionguardtest/data/election_manifest_simple.json
src/electionguardtest/data/plaintext_ballots_simple.json
tests/test_publish.py
tests/test_serializable.py

Fixes #120 
- Add make_ methods to reduce constructor issues
- Remove InitVar
- Add deserialization for ElementModP and ElementModQ
- attempt to deserialize published files
💚Thank you!

🗳 Deserialization with Ballots

---

.github/workflows/pull_request.yml
.github/workflows/release.yml
Makefile
Pipfile
Pipfile.lock
setup.py

Fixes #121 
Fixes #141 
Fixes #142 
- Reduce MacOS and Windows to only run integration tests. 
- Add make file to run all integration tests
- Add simpler commands to make file
- Fix dependency graph command issue
- Increment release number
- CI should pass. See example.
https://github.com/microsoft/electionguard-python/runs/951389340?check_suite_focus=true
💚Thank you!

✅   Balerion HotFix for Release Build Workflow

---

src/electionguard/serializable.py
tests/test_serializable.py

Fixes #165 
- read json string, object or file
- expose and test
`test_serializable`
💚Thank you!

✨ Add read json methods and tests

---

src/electionguard/decrypt_with_shares.py
src/electionguard/decryption.py
src/electionguard/decryption_share.py
tests/test_decrypt_with_secrets.py
tests/test_decryption_mediator.py

Fixes #152 
Closes #164 
✨  Exposes new functions to:
- Compute a decryption share for a ballot
- Compute a compensation share for a ballot
- Reconstruct a missing share for a ballot
- Decrypt a ballot
Examples of using these functions can be found in the decryption mediator tests.
🐛 This also happens to fix a bug in tally share reconstruction whenever multiple ballots were spoiled.
Tests have been added for ballot decryption, and updated to include multiple spoiled ballots.
💚Thank you!

Refactor decryption to support individual ballots

---

setup.py

🆙 Upgrade to 1.1.4

---

setup.py

Fixes #176 
Upgrade version to 1.1.5

Upgrade to 1.1.5

---

src/electionguard/election.py
tests/test_election.py

Fixes #186
Uses ticks to hash dates in election descriptions, adds a test.
See the test added to `test_election`
💚 Thank you!

🐛 Use ticks to hash dates in election descriptions

---

src/electionguard/election.py

Fixes #178 
*Removed the hashed parties from election.py#L576.*
*Code Review.*
💚Thank you!

Fixed issue #178

---

src/electionguard/decryption.py

Closes #198 
Adds optional arguments to allow clients to manually manage the Scheduler lifecycle.  See notes on the issue itself for more thoughts.
Existing tests all pass.
💚 Thank you!

Allow Scheduler instance to be injected into decryption functions

---

setup.py

Fixes #202 
Version bump
No changes to code or tests.
💚Thank you!

⬆️ Bump package version to 1.1.7

---

src/electionguard/tally.py

Closes #209 
Pass an optional Scheduler into tally-related methods.
This isn't my favorite solution, but it does get the job done.  Critiques are very welcome.
Tests continue to pass!
💚Thank you!

Add injectable Scheduler param to tallying

---

setup.py

Closes #211 
Does what it says on the tin
No changes to code or tests.  Verify tests still pass.
💚Thank you!

⬆️ Bump package version to 1.1.8

---

src/electionguard/group.py
src/electionguard/tracker.py
src/electionguard/words.py
tests/test_tracker.py

Fixes #82 
Follow Josh's algorithm for the tracking code
`make test`
💚Thank you!

Use consistent tracking code format

---

setup.py
tests/test_singleton.py

Fixes #215 
Upgrade package version
Shouldn't require testing

⬆️ Bump package version to 1.1.9

---

setup.py

Fixes #221 
*Please describe your pull request.*
*Describe the best way to test or validate your PR.*
💚Thank you!

bump version to 1.1.10

---

docs/Build_and_Run.md

Fixes #232 
Fixes a typo in documentation.
No testing required.
💚Thank you!

Fixed a typo

---

Pipfile
Pipfile.lock
src/electionguard/election_description_schema.json
src/electionguard/schema.py
tests/test_schema.py

Fixes #226 
Add a method to validate a manifest. 
Major points to review
- What is required
- What is string length limited
- What are the minimums.
`test_schema.py`
💚Thank you!

Validating Manifest Schema

---

setup.py

Fixes #240 
Upgrade to latest 1.1.12 version

🆙 Upgrade to 1.1.12

---

requirements.txt
setup.py

Fixes #243 
Fixes #244 
Fixes #245 
- Hot fix to ensure setup.py correctly makes package. 
- Remove requirements.txt which could cause further confusion
- Update to next version.

🔥 Hot Fix : Update package requirements in setup.py

---

setup.py

Fixes #247 
Fixes #249
Json files were not included in last release
Test with `make package` and ensure json is included in release.

Include json files and Update Version

---

Makefile

Fixes #262 
Resolve Windows build issues
This PR will be successful if the windows build is passing
💚Thank you!

🐛  Alter Windows Paths

---

src/electionguard/publish.py
tests/integration/test_end_to_end_election.py

Fixes #258
In publish(), compute directories during runtime rather than import time, to fix the results_directory argument.
Try setting the last argument of publish(), results_directory, which is what the tests now do.
💚Thank you!

Fix publish results_directory argument

---

setup.py

Fixes #107 
Update version to 1.1.16 for the next release

🆙  Update to version 1.1.16

---

data/election_manifest_simple.json
data/hamilton-county/election_manifest.json
src/electionguard/election.py
src/electionguard/election_description_schema.json
src/electionguardtest/election.py
src/electionguardtest/election_factory.py

Fixes #296 
This will hope coordinate the specification to the version of the manifest. Later this serves a lot of importance in aligning the specification and the code.
Existing tests
💚Thank you!

🛠 Add specification version to manifest / description

---

src/electionguard/decrypt_with_shares.py
src/electionguard/decryption.py
src/electionguard/decryption_mediator.py
tests/integration/test_end_to_end_election.py

Fixes #333
Cleanup some doc typos.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/electionguard-python/334)

Clean up on tests to remove useless check

---

docs/0_Configure_Election.md
docs/2_Encrypt_Ballots.md
docs/3_Cast_and_Spoil.md
docs/4_Decrypt_Tally.md
src/electionguard/ballot.py
src/electionguard/encrypt.py
src/electionguard/hash.py
tests/property/test_decrypt_with_secrets.py
tests/property/test_encrypt.py
tests/property/test_encrypt_hypotheses.py
tests/property/test_tally.py
tests/unit/test_ballot_box.py

Fixes #324 
- Refactor hash where possible
Existing test suite

Refactor hash suffix where possible

---

docs/2_Encrypt_Ballots.md
src/electionguard/ballot.py
src/electionguard/ballot_code.py
src/electionguard/ballot_compact.py
src/electionguard/encrypt.py
src/electionguardtest/election_factory.py
src/electionguardtest/sample_generator.py
tests/integration/test_end_to_end_election.py
tests/property/test_decrypt_with_secrets.py
tests/property/test_encrypt.py
tests/property/test_encrypt_hypotheses.py
tests/property/test_tally.py
tests/test_decryption_mediator.py
tests/unit/test_ballot_box.py
tests/unit/test_ballot_code.py
tests/unit/test_ballot_compact.py

Fixes #330 
- Add Compact Plaintext and Ciphertext Ballot
- Update Encryption Device and hashing mechanisms
- Isolate `create_ballot_hash` to get a single ballot hash
- Isolate `encrypt_ballot_contests` for using to encrypt all the ballot contests
In Progress

✨  Implement Compact Ballot

---

Makefile
src/electionguard/chaum_pedersen.py
src/electionguard/election.py
src/electionguard/elgamal.py
src/electionguard/encrypt.py
src/electionguard/guardian.py
src/electionguard/logs.py
src/electionguard/manifest.py
src/electionguard/schnorr.py
src/electionguard/utils.py
tests/property/test_decrypt_with_secrets.py
tests/property/test_encrypt.py
tests/property/test_hash.py

add hash tests
Fixes #365
This PR fixes some serialization issues between the c++ and python code.  Specifically fixing the serialization of dates, ensuring all numbers get hashed as hex strings, and adding some audit logs.
`make test`

Handle dates consistently

---

.github/workflows/release.yml
Makefile

Resolve issue with poetry version being too low.

Update Release Workflow for poetry issues

---

src/electionguard/hash.py
tests/property/test_hash.py

Fixes #378 
See #378 
Minor changes, all tests still pass.

hash now correctly handles integers, other iterables

---

src/electionguard/guardian.py
tests/integration/test_end_to_end_election.py

Fixes #369 
Did the changes as per request in the described issue.

Minor errors in trogdar release fixed

---

src/electionguard/election.py

Fixes #314 
Remove the specification link

🔗  Remove Broken Specification Links

---

.github/workflows/pull_request.yml

Fixes #388 
- Allow to write to security events
- Allow fast-fail to ensure all code testing is run
- Allow read actions and contents for code analysis
- Add to schedule every monday
- Ensure dispatch can run
- Ensure branches specifically target main, releases, and integration branches
Allow PR to run.

🚀 Improve Code Analysis

---

tests/property/test_discrete_log.py

Fixes #413 
- Remove warnings by instituting asyncio and remove async on tests
- Add arrange, act, assert comments for clarity
- Ensure all plaintext resolve to self instead of referencing a new variable
- Remove unneeded optional and int to q conversions
Run discrete log tests 
`poetry run pytest tests/property/test_discrete_log.py`

🐛. Resolve Warnings on Discrete Log Tests

---

README.md

Fixes N/A
*Fixes a typo in the README that broke a documentation link*
Visually inspected the rendered README

Fix link to Publish and Verify documentation

---

pyproject.toml

🆙 Update to 1.3.0

---

.github/workflows/pull_request.yml
.github/workflows/release.yml

Fixes #435
- Specify "3.9.5" as python version
- Needed to upgrade to `actions/setup-python@v2` in order to grab "3.9.5"
N/A

Upgrade actions/setup-python and specify python version as 3.9.5

---

tests/property/test_elgamal.py
tests/property/test_hash.py
tests/property/test_schnorr.py

Fixes #493 
Reorganize inter-tests imports to point directly to source.
N/A

Reorganize inter-tests imports to point directly to source

---

src/electionguard/group.py
tests/property/test_group.py

Fixes #490 
Fix double negative inside of `BaseElement.__ne__`
`make coverage`

Fix (and add tests for) BaseElement.__ne__

---

src/electionguard_tools/helpers/serialize.py

Fixes #499 
Replace default with int in serializer

♻️. Replace default with int in serializer

---

src/electionguard_verify/__init__.py
src/electionguard_verify/verify.py
tests/property/test_verify.py

Fixes #428 
Created `verify_aggregation` method and their accompanying tests. The method takes all the `Submitted Ballot` and checks that they are present in the `CiphertextTally`.

✅ Create Verifier Package: Verify Aggregation

---

src/electionguard/decryption_mediator.py

Fixes #502 
See #502 : Replace comparison operator `is` with `==` to ensure comparison of values.
Run tests.

Replace comparison operator "is" with "=="

---

.gitignore
Makefile

Fixes #498 
Create a `fetch-sample-data` command. This command migrates existing logic to an isolated command. 
The zip created will create sample-data.zip.1 if duplicated so gitignore was modified. 
This command should be run locally when running `make environment`. It is best to test directly.

💻  Add Fetch Sample Data command to MakeFile

---

src/electionguard/decryption.py
src/electionguard/key_ceremony.py
tests/unit/test_guardian.py
tests/unit/test_key_ceremony.py

Fixes #540 
- Refactor backup value to coordinate
- Refactor value to be ElementModQ effectively simplifying conversions
- Fix tests
Existing test suite is suitable

♻️  Refactor Backup Value to Coordinate

---

src/electionguard/__init__.py
src/electionguard/election.py

Fixes #386 
Add configuration to allow_overvotes to be set

⚙️ Add Configuration to Context

---

src/electionguard/schnorr.py

Fixes #514 
The current code for schnorr.py's is_valid method computes a new challenge c and now checks that this is equal to the challenge field in the proof according to the Spec
- Existing test suite should suffice

🐞 Resolve missing challenge check in Schnorr

---

Makefile

Fixes #566 
- The Mac OS issue seems to actually just be poetry failing to figure out dependencies. Moving poetry to a newer version to resolve this problem. 
The CI actually building all three tests should be evidence of the fix.

📦  Upgrade poetry to 1.1.13

---

poetry.lock
pyproject.toml
src/electionguard/__init__.py
src/electionguard/big_integer.py
src/electionguard/group.py
src/electionguard/serialize.py
tests/property/test_elgamal.py
tests/property/test_group.py

Fixes #598 
Back into the never ending serialization, the current push was to try and resolve the previous concerns around `{ data: ''}` in the BaseElement while also prepping for #524 . This takes a similar approach of using a value type to handle `BigInteger`. It also attempts to hide this a bit away from the group.py and isolate these concerns out. 
The existing test suite is fairly thorough for these items.
Currently, this is ironically failing in the deserialization round of the end to end test. This may be a false positive because both dictionaries show identical values. The output of these can be seen easily by changing the output flags on the end to end test.

🐍. Big Integer and Base Element

---

src/electionguard/constants.py
src/electionguard/serialize.py

Fixes #555 
This utilizes the new BigInteger class to handle exporting the ElectionConstants as a hex as well. 
This can be seen by running the end to end test and looking at the constants output.

♻️ Refactor ElectionGuard Constants to BigInteger

---

src/electionguard/__init__.py
src/electionguard/encrypt.py
src/electionguard/hash.py
src/electionguard/serialize.py
src/electionguard/utils.py
tests/unit/test_encrypt.py

Fixes #612 
- Add ContestData and ContestErrorType
- Migrate byte settings into utils
- Ensure that contest data can be consistently serialized and deserialized before encryption for overvotes and writeins. 
There is a new test in `test_encrypt.py`. This should be verified.

✨ Contest Data and Encoding

---

src/electionguard/elgamal.py

Fixes #639 
MAC Key Size although originally described accurately with recent changes does not represent the value. 
This change makes the code more flexible while using a more accurate name.
The existing test in `encrypt.py` that checks for integration tests this code perfectly.

🐞  Refactor MAC Key Size name

---

.github/workflows/pull_request.yml
.github/workflows/release.yml

Fixes #661 
- Update pull request workflow
- Update release workflow
Existing CodeQl workflow

🆙 Upgrade CodeQL v1 to v2

---

docs/1_Key_Ceremony.md
docs/4_Decrypt_Tally.md
src/electionguard/decryption_mediator.py
src/electionguard/election.py
src/electionguard/election_builder.py
src/electionguard_cli/cli_steps/cli_step_base.py
src/electionguard_cli/cli_steps/print_results_step.py

Fixes less vs fewer grammar typo's
nothing substantial here all existing tests pass is sufficient

Fix fewer/less grammar

---

pyproject.toml

Fixes #578 
Relies on PR #672 . This will not pass without it. 
This can be tested properly with `make build` . This is actually already an issue since `electionguard_cli` relies on `electionguard_tools`

✅ Add ElectionGuard Tools to Project

---

src/electionguard_cli/__init__.py
src/electionguard_cli/cli_models/__init__.py
src/electionguard_cli/cli_models/mark_results.py
src/electionguard_cli/cli_steps/__init__.py
src/electionguard_cli/cli_steps/mark_ballots_step.py
src/electionguard_cli/mark_ballots/__init__.py
src/electionguard_cli/mark_ballots/mark_ballot_inputs.py
src/electionguard_cli/mark_ballots/mark_ballots_election_builder_step.py
src/electionguard_cli/mark_ballots/mark_ballots_input_retrieval_step.py
src/electionguard_cli/mark_ballots/mark_ballots_publish_step.py
src/electionguard_cli/mark_ballots/mark_command.py
src/electionguard_cli/start.py
src/electionguard_tools/factories/ballot_factory.py

Fixes #619, #618
```sh
eg mark-ballots 20 congress-district-7-hamilton-county --out-dir /tmp/foo
eg mark-ballots 20 --out-dir /tmp/foo # randomly selected ballot styles
```
Based off of the code for `eg encrypt-ballots`.

⚡ Generate Plaintext Ballots in CLI

---

src/electionguard_db/mongo-init.js
src/electionguard_gui/__init__.py
src/electionguard_gui/components/__init__.py
src/electionguard_gui/components/upload_ballots_component.py
src/electionguard_gui/containers.py
src/electionguard_gui/main_app.py
src/electionguard_gui/services/__init__.py
src/electionguard_gui/services/ballot_upload_service.py
src/electionguard_gui/web/components/admin/create-election-component.js
src/electionguard_gui/web/components/admin/upload-ballots-component.js
src/electionguard_gui/web/components/admin/view-election-component.js
src/electionguard_gui/web/components/shared/navbar-component.js
src/electionguard_gui/web/services/router-service.js

Fixes #694 
Provides the ability to upload ballots to an election.
1. Create an election
2. Select the new upload icon in the upper right
3. Select a device file and ballot folder
4. Click upload
Expected: a success screen, see gif in the Description section

#694 Upload Ballots

---

src/electionguard/guardian.py
src/electionguard_gui/components/create_election_component.py

Fixes #737 
Fixes the problem with the key not being found during election creation in the GUI.
I tested this thoroughly end-to-end myself including the julia verification.

#737 Fix Key Ceremony Create Key Not Found

---

.gitignore
Makefile
src/electionguard_gui/services/ballot_upload_service.py

Fixes issue #747 
Makefile now downloads 1.0.  Also fixes an issue where you couldn't run the command multiple times.
1. Run `make fetch-sample-data`
Expected: The `/data` folder should contain `1.0`

Fix sample data to 1.0

---

src/electionguard_gui/components/upload_ballots_component.py
src/electionguard_gui/models/election_dto.py
src/electionguard_gui/services/ballot_upload_service.py
src/electionguard_gui/services/election_service.py
src/electionguard_gui/web/components/admin/upload-ballots-component.js
src/electionguard_gui/web/components/admin/view-decryption-admin-component.js
src/electionguard_gui/web/components/admin/view-election-component.js

Fixes #766 
Primarily this adds additional validation during ballot upload that the ballots match the manifest.  It also:
- Fixes an issue where error messages weren't displayed correctly on the decryption page
- Improves the UI of the election page
- Moves buttons on the menu to appropriate sections where possible
- Displays a nice message if there aren't any ballots and tallies
- Moves the title down and separates the sections more clearly
- Updates button colors from green to gray
- Move title lower on page and adjusts spacing
- Add tally date to tallies list
- Add upload date to ballots list
- Improves the UI of the decryption page
- Adjusts UI to match election page e.g. buttons to grey
- Renames "Decryption Results" to "Tally Results"
- Moves spoiled ballots into a table
- Show a …

#766 Ballot Enhancements

---

src/electionguard_gui/components/view_decryption_component.py
src/electionguard_gui/models/election_dto.py
src/electionguard_gui/web/components/admin/view-election-component.js

Fixes #779 
Previously you couldn't navigate to the decryption page.  This fixes it.
1. Navigate to an election detail page
2. Create a decryption
3. Navigate back to election page
4. Click on the decryption
Expected: You should navigate to the view decryption page

#779 View decryption

---

docs/Tablet Setup.md

Fixes #787 
Add new document for the setup of the tablets/election machines

Create New document for the tablet setup

---

.github/workflows/release.yml
Makefile

Fixes #789 
Fixes two bugs with github release workflow.
Close a release, it should pass.

Fix the release github action

---

Makefile

Fixes #793
*Please describe your pull request.*
*Describe the best way to test or validate your PR.*

🐛 #793 fix docker build-egui
