- Makefile
- Pipfile
- Pipfile.lock
- README.md
- docs/0_Configure_Election.md
- docs/1_Key_Ceremony.md
- docs/4_Decrypt_Tally.md
- docs/index.md
- mkdocs.yml
Fixes #4 
⚠️ Depends on PR #65 due to readme updates and changes to image banner
⚠️ Future Package PR will handle deployment on docs
Documentation has been established but we need to deploy for easy access. The original attempt was going to purely run off the code. Since the documentation approach was changed to be easily accessible markdown files instead of using `sphinx` or a similar generation approach, `mkdocs` was chosen for simplicity. This is supported by Read The Docs and it can be deployed to Github pages. See more here: https://www.mkdocs.org/
The principle of the setup is simple. 
- A home page (index.md) that acts as a landing page. This has some similarities to the README.md
- A configuration file to assist in deployment
- Updating the links to not be relative when above the …
> Auto Generate Documentation

- Pipfile
- Pipfile.lock
- docs/1_Key_Ceremony.md
- src/electionguard/auxiliary.py
- src/electionguard/guardian.py
- src/electionguard/key_ceremony.py
- src/electionguard/rsa.py
- tests/test_decryption_mediator.py
- tests/test_key_ceremony.py
- tests/test_rsa.py
Fixes #99  
Add RSA encryption as default method to messages between guardians for sharing of the secrets. PR originally encompassed other cards hence the branch name is a bit off. There was also a bug discovered with the test_decryption_mediator.
* test_rsa.py
💚Thank you!
> Secret Sharing in RSA

- src/electionguard/data_store.py
Fixes #102 
Resolves this warning:
> DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
- Existing test suite
💚Thank you!
> 🐛 Resolve Deprecation warning for collections

- setup.py
- src/electionguard/serializable.py
- tests/test_serializable.py
Fixes #158 
Fixes #157 
This is to allow clients more features using jsons without directly interacting with it until a different solution can be accomplished. This most importantly includes handling exporting to an object. Especially useful in web apis. 
This includes the version bump to facilitate an easy increment. 
- `test_serialize`
> ✨ Open up serialization to reduce clients from depending on jsons

- .github/workflows/pull_request.yml
- Makefile
- src/electionguardtest/sample_generator.py
Fixes #161
Closes #160 
Adds arguments to the sample generator:
```bash
$ pipenv run python ./src/electionguardtest/sample_generator.py --help
usage: sample_generator.py [-h] [-n <count>] [-s <rate>] [-a]
Generate sample ballot data
optional arguments:
-h, --help            show this help message and exit
-n <count>, --number-of-ballots <count>
The number of ballots to generate. (default: 5)
-s <rate>, --spoil-rate <rate>
The approximate percentage of total ballots to spoil instead of
cast. Provide a number from 0-100. (default: 50)
-a, --all-guardians   If specified, all guardians will be included. Otherwise, only the
threshold number will be included. (default: False)
```
Optional arguments have also been added to the Makefile: `SAMPLE_BALLOT_COUNT` and `SAMPLE_BALLOT_SPOIL_RATE`. …
> Support command line arguments in sample_generator and fix spoil rate

- src/electionguard/key_ceremony.py
Fixes #166 
- The value for challenge should be ElementModQ instead of int both for serialization and for simplicity
- Key ceremony test suite
💚Thank you!
> 🐛 Change Challenge to use an ElementModQ Value

- src/electionguard/decryption.py
Fixes #174 
When a Scheduler isn't provided to certain methods, wait to initialize a new one until the method is executing.
Linter/tests pass.
💚 Thank you!
> Avoid initializing a scheduler as a default argument

- src/electionguard/ballot.py
- src/electionguard/utils.py
- tests/test_utils.py
Fixes #190 
- Updates the `utils.to_ticks` function to use the unix epoch (seconds since January 1, 1970 UTC)
- Replaces the use of `datetime.utcnow` with `datetime.now`, as [`utcnow` is considered harmful](https://docs.python.org/3/library/datetime.html#datetime.datetime.utcnow) and ironically produces the wrong epoch timestamp.
Note: sample data will need to be regenerated, but we have several other hashing/format changes coming and should address that in one sweep.
Unit tests for `utils.to_ticks` have been augmented to cover more flavors of datetime.
💚 Thank you!
> 🕙 Use unix epoch to generate ticks

- src/electionguard/serializable.py
- tests/test_serializable.py
Fixes #187 
Updates deserialization to support the `Z` suffix in ISO-8601
Tests have been updated
💚 Thank you!
> Deserialize ISO-8601 dates ending in Z as UTC

- src/electionguard/election.py
- src/electionguard/group.py
Fixes #___
hashes were hasing on the python enumeration object which is difficult to reproduce across languages
run the tests
💚Thank you!
> Fix element mod p hash and use enum name in hash

- src/electionguard/ballot.py
- src/electionguard/ballot_code.py
- src/electionguard/ballot_compact.py
- tests/unit/test_ballot_code.py
Fixes issue #347 
Renamed `get_rotating_ballot_code` to `get_ballot_code` and `previous_code` to `code_seed`
> Fix Issue #347: Remove wording that implies ballot chaining

- src/electionguard/decrypt_with_shares.py
- src/electionguard/decryption.py
- src/electionguard/decryption_mediator.py
- src/electionguard/guardian.py
- src/electionguard/key_ceremony_mediator.py
- src/electionguard/types.py
- src/electionguardtest/decryption_helper.py
- src/electionguardtest/sample_generator.py
- tests/integration/test_end_to_end_election.py
- tests/property/test_decryption_mediator.py
- tests/unit/test_decrypt_with_shares.py
- tests/unit/test_decryption.py
Fixes #354 
This is the removal of the the guardians from being within the Decryption Mediator. 
- Created `MEDIATOR_ID` type
- Removed `ballots` (multiple) in favor of only `ballots` (singular) methods
- Remove `AVAILABLE_GUARDIAN_ID` and `MISSING_GUARDIAN_ID` to reduce exports
- Add compute share methods to Guardian
- Update tests after decryption mediator changes 
The existing test suite had to be modified but the test coverage should showcase the changes.
end_to_end and decryption tests should be focused on.
> Decryption Mediator Rework

- data/ballot_in_simple.json
- data/plaintext_ballots_simple.json
- data/plaintext_two_ballots_minimal.json
- data/plaintext_two_ballots_small.json
- src/electionguard/ballot.py
- src/electionguard/ballot_compact.py
- src/electionguard/decrypt_with_secrets.py
- src/electionguard/decrypt_with_shares.py
- src/electionguard/decryption.py
- src/electionguard/election_object_base.py
- src/electionguard/encrypt.py
- src/electionguard/manifest.py
- src/electionguard/tally.py
- src/electionguardtest/ballot_factory.py
- src/electionguardtest/election.py
- src/electionguardtest/election_factory.py
- tests/property/test_encrypt.py
- tests/property/test_encrypt_hypotheses.py
- tests/unit/test_manifest.py
Fixes #350 
The crypto hash did not have obvious problems but did not correctly ensure ordering. The item present to check for this was the sequence order. This resolves this problem by ensuring the ballot maintains the ordering allowing quick sorting. This is important to have on the ballot to ensure that without the manifest the ballot contests and selections can still be correctly sorted. This also helps solve equality problems that could present themselves and simplify things on the compact ballot. 
The approach was to add the sequence_order slowly into the ciphertext pieces and then allow this to ripple into the plaintext. A method was added to sort to ensure that …
> Crypto Hash using Sequence Order

- src/electionguard/decryption_mediator.py
- src/electionguard/election_polynomial.py
- src/electionguardtest/export.py
- tests/integration/test_end_to_end_election.py
Fixes #281 
- Add an explicit record for lagrange coefficients generated by the decryption mediator. This will now export as its own file and can be quickly exported from the mediator. This could also be used isolated in a functional way without a mediator. 
New lines were added to end-to-end integration test. This is the only test that can properly showcase an export.
> ✨ Add explicit export for Lagrange Coefficients

- src/electionguard/election.py
Fixes #418 
- Add Extended Data to allow inserting data into the electionguard context.
No testing required.
> 🗂. Add extended_data to ElectionGuard Ciphertext Context

- src/electionguard/chaum_pedersen.py
Fixes #411 
Changed the computation of the Chaum-Pederson proofs to more efficient versions saving two modular exponentiations per proof. Still computes the exact same proofs and verification stays the same.
(Note, there is a typo in the Word document that is attached to the issue: the alternative for the proof of an encryption of zero  needs to compute `v1 = (v + c1*R) mod q`.)
Run Chaum-Pedersen tests.
> 🧮 Utilize optimized encryption equations

- tests/bench/bench_chaum_pedersen.py
Fixes #443 
Instance of `BenchInput` tuple was improperly iterated that caused an error in Benchmark. Removed that line and modified some code to fix the error.
`make bench` command can be used to test and run Benchmark
> Fix Chaum Pedersen Bench

- src/electionguard/ballot.py
- src/electionguard/ballot_compact.py
Fixes #488 
Fixes #491 
fixed super() call on __eq__ on line 853 of ballot.py, which were raising DeprecationWarning and NotImplemented.
Run test_ballot_compact.py unit test. However, now it fails `line 91, in test_compact_submitted_ballot` apparently due to the nonce of submitted ballot (None) not matching the nonce of other (expanded ballot). I am submitting as a WIP. Please let me know what the tests are expected to do and the changes to the test that should be made. Can I force push any amendments or?
Thanks in advance.
> Fix super() call in ballot.py related to DeprecationWarning

- src/electionguard_tools/strategies/election.py
The initial manifest creation draws a String using emails() methods from hypothesis strategies, but it requires a list of annotated string. I added a annotated_emails method to draw a two_letter_code for annotation and a email-format string for value. 
Fixes #495 
Generate a list of annotated string for email field in contact info. 
make test
> Dataclass incompatible: Fix fields in manifest contactInfo

- src/electionguard_tools/strategies/election.py
- tests/property/test_verify.py
Fixes #501 
The cause of inequality of InternalManifests constructed from same Manifest was
https://github.com/microsoft/electionguard-python/blob/db1287d66c8aabf70a9d338bf6c249578906b3df/src/electionguard_tools/strategies/election.py#L630
Since lists are call by reference in python, shuffling `ballot_selections` affects `contest`. This changes the hash of `Contests` and creates a difference in `manifest_hash` for the `InternalManifest`.
Creating a copy of `ballot_selections` fixes this issue and made improvements to the test that uses this method.
> Fix equality of InternalManifests constructed from same Manifest

- .gitignore
- Makefile
- src/electionguard_tools/__init__.py
- src/electionguard_tools/factories/election_factory.py
- src/electionguard_tools/scripts/__init__.py
- src/electionguard_tools/scripts/sample_generator.py
Fixes #200
Add CLI params to the sample generation process to define a spec version and the sample set to use. when setting up the environment, pull down the sample data from the existing spec release from the `electionguard` spec repo.
This PR satisfies the requirement of making the sample generator configurable, however due to ongoing serialization changes, only the `hamilton-general` sample can actually be run at this time.
1. `make environment`
2. `make generate-sample-data`
Expect: sample data is output correctly to the `/results` folder.
> Allow specifying sample to use when running the generator

- Makefile
Fixes #515 
Change all commands to reference Python 3 specifically. This is to simplify issues in MacOS where the user has to specify in their environment that `python` refers to Python 3 instead of the default Python 2. 
Run any of the commands. This should happen by default by the CI
> ✅ Ensure all python commands reference Python3

- src/electionguard/election_polynomial.py
- src/electionguard_tools/scripts/sample_generator.py
- tests/integration/test_end_to_end_election.py
Fixes #520 
Change LagrangeCoefficients to stay a dictionary on output. This actually reduces some code complexity and quickly allows the guardian id to exist for the LagrangeCoefficients.
Sample data will have to regenerated following this. An issue will be made in `electionguard`
The integration test is the best place for this to be caught.
> ♻️  Add GuardianId to LagrangeCoefficientRecord

- src/electionguard/elgamal.py
- tests/integration/test_end_to_end_election.py
Fixes #547 
Pydantic causes confusion between the classes. A direct solution would be relying on exclusively pydantic set of dataclasses. This causes issues due to BaseElement. Took a more direct solution is to override the equality and enforce primarily comparing the objects at the low level. 
Test added to prevent future issues around this section.*
The integration tests performs a new test for this that checks for this error.
> 🐞 CiphertextSelection Equality due to Pydantic

- src/electionguard/ballot.py
Fixes #553 
Add extended data field to contest. This should later be updated to encrypt and decrypt at a later point. Similar non working field to `extended_data` on selection until issues #385, and #551 are complete
Existing test suite should suffice.
> 🔒 Add extended data field to contest

- src/electionguard_cli/e2e/e2e_command.py
- src/electionguard_cli/e2e/e2e_input_retrieval_step.py
Fixes #623 
Updates the `--ballots` parameter to accept either a file or a directory to pull ballots from.
Try something like `poetry run eg e2e --guardian-count=2 --quorum=2 --manifest=../data/manifest.json --ballots=../data/plaintextballots --output-record="./election_record.zip"` where ../data/plaintextballots contains files with ballots
> 📂 #623 Fix e2e to accept a directory for ballots

- src/electionguard_cli/import_ballots/import_ballots_command.py
- src/electionguard_cli/import_ballots/import_ballots_input_retrieval_step.py
- src/electionguard_cli/setup_election/output_setup_files_step.py
Fixes #634 
The guardian import was looking in a file not for all files in a folder, this fixes that.
Run something like `poetry run eg import-ballots --manifest=../data/import/manifest.json --context=../data/import/context.json --ballots-dir=../data/import/ballots --guardian-keys=../data/import/guardian_private_data --encryption-device=../data/import/device_91755434160.json --output-record=../data/import-publish-results.zip`
> 🐛 Import guardians in all files in a folder not in a file

- data/election_manifest_simple.json
- data/plaintext_ballots_simple.json
- data/plaintext_two_ballots_minimal.json
- data/plaintext_two_ballots_small.json
- src/electionguard/ballot.py
- src/electionguard/ballot_compact.py
- src/electionguard/decrypt_with_secrets.py
- src/electionguard/encrypt.py
- src/electionguard_tools/factories/ballot_factory.py
- src/electionguard_tools/strategies/election.py
Fixes #640 
`sequence_order` currently exists on contests and ballot_selections in plaintext ballots. This PR removes it from the input and instead derives the information from the manifest.
Running the end-to-end integration test will sufficiently test this since sequence order is removed from `plaintext_ballots_simple.json`.
> 🔢 #640 Remove Sequence Order from Plaintext Ballots

- src/electionguard/decrypt_with_shares.py
- src/electionguard/decryption_mediator.py
- src/electionguard_cli/cli_steps/decrypt_step.py
- src/electionguard_cli/e2e/e2e_command.py
- src/electionguard_cli/import_ballots/import_ballots_command.py
- src/electionguard_tools/scripts/sample_generator.py
- tests/integration/test_end_to_end_election.py
- tests/property/test_decryption_mediator.py
- tests/property/test_verify.py
- tests/unit/test_decrypt_with_shares.py
Fixes #637 
- Use the Manifest to strip out any selections and contests that are not in line with Manifest. This is now the default. 
- Update the CLI and tests in line with this
- Includes boyscout rename in Sample Generator
Before
After
- Existing test suite should specifically run through this.
> 🗳. Remove placeholders from decrypted ballots and tallies

- Makefile
- README.md
Supports #620 
Minor fix to the makefile, which didn't run on Windows.  The problem was that the `>` in the embedded python script that determines 32 or 64 bit was being stripped out along with everything after it in any given statement.  It was as if something somewhere detected a cross-site scripting attack and tried to sanitize the input, but did it poorly.  I searched for a while but couldn't find any solutions, so I just removed it, since it wasn't really doing anything anyway.
Incidentally, this PR doesn't address gmpy2, and thus supports but doesn't fix the ticket as written.
Run something simple on Windows like `make auto-lint`.  Previously it would give an error about `/5` not being a valid argument or something.
> 🪟 #620 Fix Makefile on Windows

- Makefile
Fixes #650 
Removes the deprecated `generate-sample-data` target and cleans up some extra tabs
Simple change no testing required
> 🎯 Remove generate sample data target

- src/electionguard_cli/__init__.py
- src/electionguard_cli/cli_steps/output_step_base.py
- src/electionguard_cli/setup_election/__init__.py
- src/electionguard_cli/setup_election/output_setup_files_step.py
- src/electionguard_cli/setup_election/setup_election_command.py
- src/electionguard_cli/setup_election/setup_input_retrieval_step.py
- src/electionguard_cli/setup_election/setup_inputs.py
Fixes #648 
The guardian private key were previously output into the same directory as the context and manifest.  In this PR all guardian private keys are put into `[out]/private_guardian_data` and everything else is output into `[out]/public_encryption_package`.  Furthermore if you specify `--zip` as a parameter to the `eg setup` command, then it will zip up everything in `[out]/public_encryption_package`, place it into `[out]\public_encryption_package.zip`, and delete the source directory.
Run `poetry run eg setup --guardian-count=2 --quorum=2 --manifest=data/election_manifest_simple.json  --out=../data/setup-election-out --zip`
You should get back something like this:
> 🧑‍💻 #648 election setup package separation

- src/electionguard/big_integer.py
- tests/property/test_hash.py
Fixes #653  - Previously 250 in `electionguard`
- Resolve issue that results from big-integers since they can be treated as byte strings. Leading zeros could be added but result in different results. 
- Add tests to demonstrate
The new hash tests replicate the situation displayed in 653
> 🐞 Resolve hex string/bytes conversion

- src/electionguard/manifest.py
- src/electionguard_cli/cli_steps/print_results_step.py
- src/electionguard_cli/e2e/e2e_command.py
- src/electionguard_cli/import_ballots/import_ballots_command.py
- tests/unit/test_manifest.py
Addresses #659
Now when you import ballots and do a tally the CLI will display contest names and candidate names rather than the id's.
New tests cover most of the core functionality, however run an import to be sure.
> 🖨️ #29 print names

- Makefile
- src/electionguard_cli/__init__.py
- src/electionguard_cli/setup_election/__init__.py
- src/electionguard_cli/setup_election/output_setup_files_step.py
- src/electionguard_cli/setup_election/setup_election_command.py
- src/electionguard_cli/setup_election/setup_input_retrieval_step.py
- src/electionguard_cli/setup_election/setup_inputs.py
Fixes #667 
In the election setup CLI command this replaces the `--out` parameter with a `--package-dir` param and a `--keys-dir` param.  Also, it now prompts prior to overwriting existing guardian private keys.
Run `make eg-setup-simple-election`, it should pass
> 💻 #667 Separate the output dir params of election setup

- src/electionguard/serialize.py
Fixes #657 
- Indent in json dump activates a type of pretty print on the json this adds carriage returns. 
https://docs.python.org/3/library/json.html
This can be validated by checking JSON output.
> 🐞 Remove carriage Return in JSON

- Makefile
na
Sample data was previously being double-zipped and then in this repo double unzipped.  That was fixed recently and that caused CI to fail.  This fixes it by removing the double-unzipping.
CI should pass.
> Fix sample data CI failure

- src/electionguard/key_ceremony_mediator.py
- src/electionguard_gui/components/create_key_ceremony_component.py
- src/electionguard_gui/components/key_ceremony_details_component.py
- src/electionguard_gui/components/key_ceremony_list_component.py
- src/electionguard_gui/containers.py
- src/electionguard_gui/main_app.py
- src/electionguard_gui/services/key_ceremony_service.py
- src/electionguard_gui/web/components/admin/admin-home-component.js
- src/electionguard_gui/web/components/guardian/guardian-home-component.js
- src/electionguard_gui/web/components/shared/key-ceremony-details-component.js
- src/electionguard_gui/web/components/shared/key-ceremony-list-component.js
Fixes #687 
Once all guardians have joined a key ceremony the admin will now announce them and generate "other_keys" which in the next step (6b, #688) the guardians will use to create backups.  This PR also adds a "status" field so a user can track the back-and-forth communication between guardians and admins.
1. Create a key ceremony with 2 guardians
2. Start egui for 2 guardians
3. Have each guardian join the key ceremony
Expected #1: all UI's should now show a status field "waiting for guardians to create backups" like this:
Expected #2: The database should now have a field for `other_keys` like this:
> #687 Announce Guardians (#6a)

- src/electionguard_cli/cli_steps/mark_ballots_step.py
- src/electionguard_tools/factories/ballot_factory.py
Fixes #702
`eg mark-ballots` doesn't undervote or null vote anymore.
Besides verifying that this fixes #702, double-check that this doesn't accidentally reduce the set of ballots we test against.
> #702 Make `mark-ballots` selections match `number_elected`

- src/electionguard_gui/components/create_key_ceremony_component.py
- src/electionguard_gui/components/key_ceremony_details_component.py
- src/electionguard_gui/containers.py
- src/electionguard_gui/main_app.py
- src/electionguard_gui/models/key_ceremony_dto.py
- src/electionguard_gui/models/key_ceremony_states.py
- src/electionguard_gui/services/authorization_service.py
- src/electionguard_gui/services/db_serialization_service.py
- src/electionguard_gui/services/key_ceremony_service.py
- src/electionguard_gui/services/key_ceremony_state_service.py
- src/electionguard_gui/services/service_base.py
Fixes #688 
In the GUI once the admin has announced the guardians and shared their public "other" keys, the guardians will now use those other keys to create backups and place them in the database.  This additionally starts to refactor the exceedingly long and complicated KeyCeremonyDetailsComponent by moving logic into other services such as a new KeyCeremonyStateService that will be expanded in subsequent PR's.
Note: This PR is stacked on PR #707 please retarget this to main prior to merging.
1. Have an admin create a key ceremony in the GUI
2. Have all guardians log in
Expected: the UI should finish in a state that looks like this:
> #688 6b Guardian Generate Backups

- src/electionguard_gui/components/upload_ballots_component.py
- src/electionguard_gui/models/decryption_dto.py
- src/electionguard_gui/services/ballot_upload_service.py
- src/electionguard_gui/web/components/admin/upload-ballots-component.js
Fixes #726 
This splits out uploaded ballots into smaller records in mongo.
Upload more than ~20 ballots in the GUI, it should work.
> #726 support more ballots in GUI

- src/electionguard_gui/web/components/guardian/view-decryption-guardian-component.js
Fixes #729 
Added the missing parameter so that it will not throw an exception as well as refresh the decryption when it loads it.
> Add the missing parameter

- src/electionguard_gui/components/create_election_component.py
- src/electionguard_gui/containers.py
- src/electionguard_gui/services/gui_setup_input_retrieval_step.py
Fixes #731 
This reuses the guardians data from the key ceremony rather than creating new guardians during election creation.
Run an end-to-end test and validate it with the Mitre verifier.  There should be no problem with the public key.
> Reuse guardians rather than recreating them during election creation

- src/electionguard/logs.py
- src/electionguard_gui/Dockerfile
- src/electionguard_gui/components/component_base.py
- src/electionguard_gui/components/key_ceremony_details_component.py
- src/electionguard_gui/components/view_decryption_component.py
- src/electionguard_gui/containers.py
- src/electionguard_gui/main_app.py
- src/electionguard_gui/services/ballot_upload_service.py
- src/electionguard_gui/services/eel_log_service.py
- tests/unit/electionguard/test_logs.py
Supports #739
Couldn't repro the 739 bug, so this adds several features that will help us if it occurs again:
* If an error occurs during ballot decryption the system will now log it as an error and continue processing
* This updates GUI logging to combine it with the regular EG logging
* This updates GUI logging to send logs to the filesystem
Run the GUI, you should see file system logs at `egui_mnt\data\logs`
> #739 Logging

- src/electionguard_gui/models/election_dto.py
- src/electionguard_gui/services/decryption_stages/decryption_s2_announce_service.py
Fixes #743 
Guardians previously needed to be named with numbers else the election verification would fail when validating the Lagrange Coefficients stating that the guardian_id needed to be numeric.  This fixes it by having the admin look up the guardian's sequence order and announcing guardians with that value instead of the guardian's alpha-numeric identifier.
Run an end-to-end election with guardians with alpha-numeric strings and validate it in Julia.  Expected: it should validate.
> #743 Fix Guardian ids in Lagrange Coefficients

- src/electionguard_gui/models/decryption_dto.py
- tests/unit/electionguard_gui/test_decryption_dto.py
Fixes #753 
Previously you couldn't export an election record unless there were spoiled ballots.  Now you can.
Do an election record export with an election that contains no spoiled ballots.
> #753 Fix issue with exporting with no spoiled ballots

- src/electionguard/manifest.py
Fixes #751 
Removing the low-level logging improves performance by 31% (from 20.7 seconds to 15.5).  Here's perf before for 10 ballots:
```
20.76447 decryption_s2_announce_service.py - run() - get_tally
0.71651 decryption_stage_base.py - get_tally() - init CiphertextTally
18.97710 decryption_stage_base.py - get_tally() - batch_append
18.56782 tally.py - batch_append() - cast_ballot_selections loop
18.56729 tally.py - batch_append() - should collect
3.29177 ballot_validator.py - ballot_is_valid_for_election() - ballot_is_valid_for_style
15.27533 ballot_validator.py - ballot_is_valid_for_election() - is_valid_encryption
0.00004 ballot.py - is_valid_encryption() - mismatching ballot hash
0.00112 ballot.py - is_valid_encryption() - mismatching crypto hash
14.07134 ballot.py - …
```
> Decrypt Perf Improvement - Remove low level logging

- src/electionguard_gui/services/plaintext_ballot_service.py
- src/electionguard_gui/web/components/shared/view-plaintext-ballot-component.js
- tests/unit/electionguard_gui/test_decryption_dto.py
- tests/unit/electionguard_gui/test_plaintext_ballot_service.py
Fixes #755 
Previously contests that had write-in selections without any votes would fail to display.  Now contests with write-in selections and no votes will show zero write-ins.  Contests without any write-in candidates will continue to not display anything.
A good place to view this in action is for spoiled ballots.  Here's how it looks with a contest with no write-in selections vs a contest with write-in selections but no votes:
> #755 Zero Write-Ins

- src/electionguard_gui/services/plaintext_ballot_service.py
- src/electionguard_gui/web/components/shared/view-plaintext-ballot-component.js
- tests/unit/electionguard_gui/test_plaintext_ballot_service.py
Fixes #764 
The report screen had a bug where it was removing contests that had identical names.  It no longer does this.
Run an election with a manifest that contains duplicate contest names.  They will now show up again.
> #764 Stop Removing Duplicate Contests in Report

- src/electionguard_gui/components/guardian_home_component.py
- src/electionguard_gui/components/key_ceremony_details_component.py
- src/electionguard_gui/main_app.py
- src/electionguard_gui/web/components/guardian/guardian-home-component.js
Fixes #768 
The underlying issue was that Eel in Python would die when the system was resuming from sleep.  The web-based UI then looked like it was still working when in fact the server had crashed.  That gave the appearance of key ceremonies and decryptions not appearing on guardian devices when they should have, when in fact the issue was much larger.
The server-side solution is to disallow eel from ever exiting of its own accord.  This allows eel to resume from system sleep, although it has the consequence that the user must now explicitly hit Ctrl+C to end the app.
The client-side solution is to watch for system resume events and when they occur refresh the page.  This solution also adds a refresh button for convenience, although the prior solutions should warrant it unnecessary.
1. …
> #768 - System now successfully resumes from sleep on guardian page

- poetry.lock
- pyproject.toml
- src/electionguard_gui/__init__.py
- src/electionguard_gui/containers.py
- src/electionguard_gui/main_app.py
- src/electionguard_gui/services/__init__.py
- src/electionguard_gui/services/version_service.py
- src/electionguard_gui/web/components/shared/footer-component.js
- src/electionguard_gui/web/index.html
Fixes #762
Shows the version info when you run via `git egui` (not via docker, although we could add that with very little effort)
1. Run `git egui`
Expected, a git sha hash like this:
> #762 Version Info

- src/electionguard_gui/components/create_election_component.py
Fixes #742 
This fixes the bug where a creating a second election internally overwrites the election package of any prior elections.
1. Create key ceremony
2. Create election
3. Create a 2nd key ceremony
4. Create a 2nd election
5. Go to 1st election
6. Export 1st election's encryption page
7. Encrypt and upload ballots based the exported encryption package to the 1st election
8. Perform a decryption
Expected: this previously caused an infinite loop.  Now it does not.
> #742 - Fix Encryption Package Overwrite Bug
